import OpenAI from 'openai';
import type { GenogramData } from '../types/genogram';

// NOTE: In a production environment, this should be a backend call to hide the API key.
// For this demo, we will use a client-side call or a mock if no key is provided.

export const generateGenogramPrompt = (data: GenogramData) => {
  let prompt = `Analyze the following family genogram data based on DSM-5-TR psychological patterns. 
  Focus on attachment styles, intergenerational trauma, and potential behavioral patterns.
  
  Family Members:
  `;

  data.people.forEach(p => {
    prompt += `- ${p.name} (${p.age || 'Age Unknown'}, ${p.gender}, ${p.status}). Attributes: ${p.attributes?.join(', ') || 'None'}\n`;
  });

  prompt += `\nRelationships:\n`;
  data.relations.forEach(r => {
    const source = data.people.find(p => p.id === r.sourceId)?.name || 'Unknown';
    const target = data.people.find(p => p.id === r.targetId)?.name || 'Unknown';
    prompt += `- ${source} is ${r.type} to ${target}\n`;
  });

  prompt += `
  Provide a concise psychological analysis. 
  1. Identify potential patterns (e.g., triangulation, cut-offs, enmeshment).
  2. Suggest areas for further exploration.
  3. Include a disclaimer that this is not a medical diagnosis.
  `;

  return prompt;
};

export const analyzeGenogram = async (data: GenogramData, apiKey?: string) => {
  if (!apiKey) {
    // Mock Response if no API key is provided
    return new Promise<string>((resolve) => {
      setTimeout(() => {
        resolve(`**AI Analysis (Simulation Mode)**
        
Based on the structure provided, here are some potential observations:

1. **Family Structure**: The genogram shows a multi-generational structure. Ensure all siblings are accounted for to understand birth order effects.
2. **Relational Patterns**: There appear to be specific relational lines drawn. If "conflict" lines are present, consider exploring the root cause of these tensions.
3. **DSM-5-TR Note**: While this tool helps visualize patterns, specific diagnoses like *Adjustment Disorders* or *Relational Problems* require clinical evaluation.

*Disclaimer: This analysis is generated by AI for educational purposes and is not a clinical diagnosis.*`);
      }, 1500);
    });
  }

  const openai = new OpenAI({
    apiKey: apiKey,
    dangerouslyAllowBrowser: true // Only for this demo app
  });

  const prompt = generateGenogramPrompt(data);

  try {
    const completion = await openai.chat.completions.create({
      messages: [{ role: "system", content: "You are a psychological assistant expert in family systems and DSM-5-TR." }, { role: "user", content: prompt }],
      model: "gpt-4",
    });

    return completion.choices[0].message.content || "No analysis generated.";
  } catch (error) {
    console.error("AI Error:", error);
    return "Error generating analysis. Please check your API key.";
  }
};
